### ISSUE TITLE
LastPass service only imports password types

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/importer#1]
Currently only password/logins/websites types are supported in LastPass. Credit cards, addresses, secure notes, and others are skipped. This should be fixed when the following PR is merged from the upstream library used for this project: https://github.com/detunized/password-manager-access/pull/86

**Comment by detunized** [comment]
The version 10.3.0 exposes all the secure notes but in a weird way. It basically matches the LP internal structure. Everything is an account, even when it makes no sense. Example:

```
3:
        id: 6818874320685109187
      name: card1
  username: 
  password: 
       url: http://sn
      path: folder
     notes: NoteType:Credit Card
Language:en-US
Name on Card:richie rich
Type:visa
Number:1234567890
Security Code:123
Start Date:January,2012
Expiration Date:August,2040
Notes:pfpfpfpfpf
  favorite: False
    shared: False
```

The `Notes` field need to be parsed. To get access to this pass the `ParseOptions` with `ParseSecureNotesToAccount` set to `false`.

In theory it would be possible to add this functionality to the library but that's a bit of work and testing. The format is rather loose.

**Comment by kspearrin** [comment]
Yes, this is what I expect for our use case here. Our importer can handle the weird notes field for other types.
